// front/src/views/pre/Pay.vue
<style scoped>
  .resp {
    position:relative;
    height:0;
    padding-top:90vh;
    background: white;
  }
  .resp>iframe {
    position:absolute;
    top:0;
    left:0;
    width:100%;
    height:100%;
    border: none;
  }
  .mt {
    margin-top: 1em;
  }
</style>
<template>
  <v-container>
    <v-dialog v-model="dialog" persistent width="1200">
      <div class="resp"><iframe :src="iframe"></iframe></div>
    </v-dialog>
    <div class="text-h6">注文内容をご確認ください。</div>
    <v-row justify="space-around" row="center">
      <v-col xs="12" sm="8" lg="4" md="5">
        <v-card>
          <v-card-title>{{ email }}</v-card-title>
          <v-card-text>
            <v-simple-table>
              <thead>
                <tr>
                  <th class="text-left">商品ID</th>
                  <th class="text-left">商品名</th>
                  <th class="text-left">価格</th>
                  <th class="text-left">購入数</th>
                  <th class="text-left">小計</th>
                </tr>
              </thead>
              <tbody>
                <tr v-for="item in desserts" :key="item.id">
                  <td>{{ item.id }}</td>
                  <td>{{ item.title }}</td>
                  <td>{{ item.price }}</td>
                  <td>{{ item.count }}</td>
                  <td>{{ item.subtotal }}</td>
                </tr>
              </tbody>
            </v-simple-table>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
    <div class="text-h6">注文内容に誤りがなければ支払情報を入力して支払をクリックしてください。</div>
    <v-row justify="space-around" row="center">
      <v-col xs="12" sm="8" lg="4" md="5">
        <v-card>
          <v-card-text>
            <div id="card-element"></div>
            <div id="card-errors" role="alert"></div>
            <v-btn class="pink white--text mt" @click='submit' :disabled='loading' :loading='loading'>支払</v-btn>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>
  </v-container>
</template>
<script>
  import axios from "axios";
  
  import Swal from "sweetalert2";
  import Vue from "vue";

  export default {
    data: () => ({
      loading: false,
      desserts: [{id: 0, title: 'Now loading', price: 0, count: 0, subtotal: 0,},],
      total: 0,
      stripe: Stripe(Vue.prototype.$pk),
      card: null,
      dialog: false,
      iframe: null,
      intent: null,
      email: 'Now loading...'
    }),
    mounted() {
      // card element
      const elements = this.stripe.elements();
      this.card = elements.create("card");
      this.card.mount("#card-element");
      this.card.on('change', function(event) {
        var displayError = document.getElementById('card-errors');
        if (event.error) {
          displayError.textContent = event.error.message;
        } else {
          displayError.textContent = '';
        }
      });
      var self = this;
      window.addEventListener('message', function(ev) {
        if (ev.data === '3DS-authentication-complete') {
          self.dialog = false;
          self.stripe.retrievePaymentIntent(self.intent).then(result => {
            if (result.paymentIntent.status !== void 0 && result.paymentIntent.status === 'succeeded') {
              Swal.fire({
                title: "決済完了",
                html: "カード決済が完了しました。3秒後にQRコード画面に移動します。",
                showConfirmButton: false,
                showCloseButton: false,
                timer: 3000,
                onClose: closemes
              });
              function closemes(){
                this.$router.push("/qr");
              }
            } else {
              Swal.fire({
                title: "Error",
                html: "カード決済時にエラーが発生しました。別のカードをお試しいただくか、カード会社にお問い合わせください。",
                showConfirmButton: false,
                showCloseButton: false,
              });
            }
          });
        }
      }, false);
    },
    created() {
      this.$session.start();
      if (!this.$session.has("token")) this.$router.push("/login");
      axios.get("/api/order", {headers: { Authorization: "JWT " + this.$session.get("token") }}).then(response => {
        if(response.data.pay !== null)
          this.$router.push("/qr");
        this.email = response.data.email;
        this.desserts = [];
        response.data.userproducts.forEach(i => {
          this.desserts.push({id: i.product.id, title: i.product.title, price: i.price, count: i.count, subtotal: i.price * i.count});
          this.total += i.price * i.count;
        });
        this.desserts.push({count: "合計", subtotal: this.total});
      }).catch(e => {
        if (e.response.status === 401) this.$router.push("/login");
      });
    },
    methods: {
      submit() {
        this.loading = true;
        this.stripe.createPaymentMethod({
          type: 'card',
          card: this.card
        }).then(result => {
          axios.post("/api/pay", {token: result.paymentMethod.id}, {headers: { Authorization: "JWT " + this.$session.get("token") }}).then(res => {
            this.loading = false;
            Swal.fire({
              title: "決済完了",
              html: "カード決済が完了しました。3秒後にQRコード画面に移動します。",
              showConfirmButton: false,
              showCloseButton: false,
              timer: 3000,
              onClose: closemes
            });
            function closemes(){
              this.$router.push("/qr");
            }
          }).catch(e => {
            this.loading = false;
            if (e.response.status === 401) {
              this.$router.push("/login");
            } else if(e.response.data[0] === "req") {
              this.stripe.retrievePaymentIntent(e.response.data[1]).then(r => {
                this.intent = r.paymentIntent.client_secret;
                this.iframe = r.paymentIntent.next_action.redirect_to_url.url;
                this.dialog = true;
              });
            } else {
              Swal.fire({
                title: "Error",
                html: "カード決済時にエラーが発生しました。別のカードをお試しいただくか、カード会社にお問い合わせください。<br>エラーメッセージ<br>"+e.response.data[0],
                showConfirmButton: false,
                showCloseButton: false,
              });
            }
          });
        }).catch(e => {
          this.loading = false;
        });
      }
    }
  };
</script>

// src/routes/pre/pay/+page.svelte
<script lang="ts">
import type { Stripe, StripeCardElement } from '@stripe/stripe-js';
import { onMount } from 'svelte';
import OrderTable from '#lib/components/OrderTable.svelte';
import { toasts } from '#lib/stores/toast.svelte.js';
import { goto } from '$app/navigation';
import type { PageData } from './$types';

let { data }: { data: PageData } = $props();

let stripe: Stripe | null = null;
let card: StripeCardElement | null = null;
let cardError = $state('');
let loading = $state(false);
let show3ds = $state(false);
let iframeUrl = $state('');
let intentSecret = '';

async function onSucceeded() {
	toasts.success('決済完了', 'カード決済が完了しました。3秒後にQRコード画面に移動します。');
	setTimeout(() => goto('/pre/qr'), 3000);
}

onMount(() => {
	if (!data.stripeConfigured || !data.publishableKey) return;

	(async () => {
		const { loadStripe } = await import('@stripe/stripe-js');
		stripe = await loadStripe(data.publishableKey);
		if (!stripe) return;
		card = stripe.elements().create('card');
		card.mount('#card-element');
		card.on('change', (event) => {
			cardError = event.error?.message ?? '';
		});
	})();

	const onMessage = (ev: MessageEvent) => {
		if (ev.data !== '3DS-authentication-complete' || !stripe) return;
		show3ds = false;
		stripe.retrievePaymentIntent(intentSecret).then((result) => {
			if (result.paymentIntent?.status === 'succeeded') {
				onSucceeded();
			} else {
				toasts.error(
					'エラー',
					'カード決済時にエラーが発生しました。別のカードをお試しいただくか、カード会社にお問い合わせください。',
				);
			}
		});
	};
	window.addEventListener('message', onMessage);
	return () => window.removeEventListener('message', onMessage);
});

async function submit() {
	if (!stripe || !card) return;
	loading = true;
	try {
		const method = await stripe.createPaymentMethod({ type: 'card', card });
		if (method.error) {
			cardError = method.error.message ?? '';
			loading = false;
			return;
		}
		const res = await fetch('/api/pay', {
			method: 'POST',
			headers: { 'content-type': 'application/json' },
			body: JSON.stringify({ token: method.paymentMethod.id }),
		});
		if (res.ok) {
			loading = false;
			await onSucceeded();
			return;
		}
		const body = await res.json();
		if (res.status === 401) {
			goto('/login?redirect=/pre/pay');
		} else if (Array.isArray(body) && body[0] === 'req') {
			const r = await stripe.retrievePaymentIntent(body[1]);
			intentSecret = r.paymentIntent?.client_secret ?? body[1];
			const nextAction = r.paymentIntent?.next_action;
			iframeUrl = nextAction?.redirect_to_url?.url ?? '';
			show3ds = true;
		} else {
			const msg = Array.isArray(body) ? body[0] : (body?.message ?? '不明なエラー');
			toasts.error('エラー', `カード決済時にエラーが発生しました。<br>${msg}`);
		}
	} catch {
		toasts.error('エラー', 'カード決済時にエラーが発生しました。');
	} finally {
		loading = false;
	}
}
</script>

<svelte:head>
	<title>お支払い · mogiri</title>
</svelte:head>

<h1>注文内容をご確認ください</h1>
<article>
	<h2>{data.email}</h2>
	<OrderTable lines={data.order.lines} total={data.order.total} />
</article>

<article>
	<h2>お支払い情報</h2>
	{#if !data.stripeConfigured}
		<p>
			<mark>
				Stripe が設定されていません。<code>STRIPE_SECRET_KEY</code>
				と
				<code>PUBLIC_STRIPE_PUBLISHABLE_KEY</code>
				を設定してください。
			</mark>
		</p>
	{:else}
		<div id="card-element"></div>
		{#if cardError}
			<p role="alert"><mark>{cardError}</mark></p>
		{/if}
		<button type="button" disabled={loading} aria-busy={loading} onclick={submit}>支払</button>
	{/if}
</article>

{#if show3ds}
	<dialog open>
		<article>
			<iframe src={iframeUrl} title="3D Secure"></iframe>
		</article>
	</dialog>
{/if}

<style>
/* Stripe が iframe を差し込む枠。入力欄に見えるよう Pico の入力欄の線を借りる */
#card-element {
	margin-bottom: var(--pico-spacing);
	border: var(--pico-border-width) solid var(--pico-form-element-border-color);
	border-radius: var(--pico-border-radius);
	padding: var(--pico-form-element-spacing-vertical) var(--pico-form-element-spacing-horizontal);
}
/* 3D セキュアの画面。カード会社のページをそのまま重ねて出す */
iframe {
	display: block;
	width: 100%;
	height: 80vh;
	border: 0;
}
</style>
